---
title: "Code Readme"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Scripts

**assemble_OTU_data.R** - contains a short example of assembling OTU clusters data with the corresponding taxonomies and metadata, as well as some simple filtering steps to remove extraction controls and biological spike ins. 

**plot_maps.R** 
Contains the code to plot the maps included in the data paper manuscript.

**plot_taxonomies.R** 
Contains the code to download ncbi taxonomies and plot the order-level trees included in the data paper manuscript. 

**sampling_efficiency.R**
Contains the code to run the technical validation of spatial sampling efficiency of the IBA surveys. Also plots the figures contained in the manuscript. 

**plot_composition_charts.R**
Contains the code to compute the taxonomic composition of the datasets and generate the bar charts included in the manuscript.

**get_iba_co1_data_fxn.R**
Contains the code for a function that assembles OTU clusters data from processed IBA data and metadata. Includes the possibility of removing spike-in clusters and calibrating read numbers with the spike-in data.
